2024-11-18 17:11:17,395 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Urban\Module_12\module_12_4.py", line 22, in test_run
    t_run = Runner(1111, 5)
  File "D:\Urban\Module_12\tournament.py", line 7, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-18 17:11:17,395 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Urban\Module_12\module_12_4.py", line 12, in test_walk
    t_walk = Runner('Ivan', -5)
  File "D:\Urban\Module_12\tournament.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
